const  Conditions =[
	{
		code : 1000,
		day : "Sunny",
		night : "Clear",
		iconDay : "day/sunny.png",
        iconNight : "night/moon.png",
	},
	{
		code : 1003,
		day : "Partly cloudy",
		night : "Partly cloudy",
		iconDay: "day/Clouds.png",
        iconNight : "night/Clouds.png",
	},
	{
		code : 1006,
		day : "Cloudy",
		night : "Cloudy",
		iconDay : "day/Clouds.png",
        iconNight : "night/Clouds.png",
	},
	{
		code : 1009,
		day : "Overcast",
		night : "Overcast",
		iconDay : "day/Clouds.png",
        iconNight : "night/Clouds.png",
	},
	{
		code: 1030,
		day : "Mist",
		night : "Mist",
		iconDay : "night/Clouds.png",
        iconNight : "night/Clouds.png",
	},
	{
		code : 1063,
		"day" : "Patchy rain possible",
		"night" : "Patchy rain possible",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1066,
		"day" : "Patchy snow possible",
		"night" : "Patchy snow possible",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1069,
		"day" : "Patchy sleet possible",
		"night" : "Patchy sleet possible",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1072,
		"day" : "Patchy freezing drizzle possible",
		"night" : "Patchy freezing drizzle possible",
		iconDay :  "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1087,
		"day" : "Thundery outbreaks possible",
		"night" : "Thundery outbreaks possible",
        iconDay: "day/Thunder.png",
        iconNight : "night/Thunder.png",
	},
	{
		code : 1114,
		"day" : "Blowing snow",
		"night" : "Blowing snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1117,
		"day" : "Blizzard",
		"night" : "Blizzard",
		iconDay :  "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1135,
		"day" : "Fog",
		"night" : "Fog",
		iconDay : "day/Clouds.png",
        iconNight : "night/Clouds.png",
	},
	{
		code : 1147,
		"day" : "Freezing fog",
		"night" : "Freezing fog",
		iconDay : "day/Clouds.png",
        iconNight : "night/Clouds.png",
	},
	{
		code : 1150,
		"day" : "Patchy light drizzle",
		"night" : "Patchy light drizzle",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1153,
		"day" : "Light drizzle",
		"night" : "Light drizzle",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1168,
		"day" : "Freezing drizzle",
		"night" : "Freezing drizzle",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1171,
		"day" : "Heavy freezing drizzle",
		"night" : "Heavy freezing drizzle",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1180,
		"day" : "Patchy light rain",
		"night" : "Patchy light rain",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1183,
		"day" : "Light rain",
		"night" : "Light rain",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1186,
		"day" : "Moderate rain at times",
		"night" : "Moderate rain at times",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1189,
		"day" : "Moderate rain",
		"night" : "Moderate rain",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1192,
		"day" : "Heavy rain at times",
		"night" : "Heavy rain at times",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1195,
		"day" : "Heavy rain",
		"night" : "Heavy rain",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1198,
		"day" : "Light freezing rain",
		"night" : "Light freezing rain",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1201,
		"day" : "Moderate or heavy freezing rain",
		"night" : "Moderate or heavy freezing rain",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1204,
		"day" : "Light sleet",
		"night" : "Light sleet",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1207,
		"day" : "Moderate or heavy sleet",
		"night" : "Moderate or heavy sleet",
		iconDay : "day/Rain.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1210,
		"day" : "Patchy light snow",
		"night" : "Patchy light snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1213,
		"day" : "Light snow",
		"night" : "Light snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1216,
		"day" : "Patchy moderate snow",
		"night" : "Patchy moderate snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1219,
		"day" : "Moderate snow",
		"night" : "Moderate snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1222,
		"day" : "Patchy heavy snow",
		"night" : "Patchy heavy snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1225,
		"day" : "Heavy snow",
		"night" : "Heavy snow",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1237,
		"day" : "Ice pellets",
		"night" : "Ice pellets",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1240,
		"day" : "Light rain shower",
		"night" : "Light rain shower",
		iconDay : "./day/Snow.png",
        iconNight : "night/Rain.png",
	},
	{
		code : 1243,
		"day" : "Moderate or heavy rain shower",
		"night" : "Moderate or heavy rain shower",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1246,
		"day" : "Torrential rain shower",
		"night" : "Torrential rain shower",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1249,
		"day" : "Light sleet showers",
		"night" : "Light sleet showers",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1252,
		"day" : "Moderate or heavy sleet showers",
		"night" : "Moderate or heavy sleet showers",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1255,
		"day" : "Light snow showers",
		"night" : "Light snow showers",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1258,
		"day" : "Moderate or heavy snow showers",
		"night" : "Moderate or heavy snow showers",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1261,
		"day" : "Light showers of ice pellets",
		"night" : "Light showers of ice pellets",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1264,
		"day" : "Moderate or heavy showers of ice pellets",
		"night" : "Moderate or heavy showers of ice pellets",
		iconDay : "./day/Snow.png",
        iconNight : "night/Snow.png",
	},
	{
		code : 1273,
		"day" : "Patchy light rain with thunder",
		"night" : "Patchy light rain with thunder",
		iconDay : "./day/Thunder.png",
        iconNight : "night/Thunder.png",
	},
	{
		code : 1276,
		"day" : "Moderate or heavy rain with thunder",
		"night" : "Moderate or heavy rain with thunder",
		iconDay : "./day/Thunder.png",
        iconNight : "night/Thunder.png",
	},
	{
		code : 1279,
		"day" : "Patchy light snow with thunder",
		"night" : "Patchy light snow with thunder",
		iconDay : "./day/Thunder.png",
        iconNight : "night/Thunder.png",
	},
	{
		code : 1282,
		"day" : "Moderate or heavy snow with thunder",
		"night" : "Moderate or heavy snow with thunder",
		iconDay : "./day/Thunder.png",
        iconNight : "night/Thunder.png",
	}]
export default Conditions